- name: Install java  - openjdk
  apt:
    name: "{{ java_openjdk_packages }}"
    state: latest
    force: yes

- name: Set java home
  lineinfile:
    backup: yes
    dest: "/etc/environment"
    state: present
    regexp: '^JAVA_HOME'
    line: 'JAVA_HOME="/usr/lib/jvm/java-{{ java_version }}-openjdk-amd64/"'
